# set style
layout=modern
icon_theme=material
icon_style=mixed
window_top_bar=auto
greenandgrumpy=yes

# show OSC when moving mouse
minmousemove=1
deadzonesize=0

# don't show OSC on playback start
osc_on_start=no

# don't scale OSC
vidscale=no

# enable/disable interface items
jump_buttons=no
chapter_skip_buttons=yes
chapter_softrepeat=no
download_button=no
screenshot_button=no
ontop_button=no
speed_button=no

# set theme
playpause_size=32
midbuttons_size=28
sidebuttons_size=24
chapter_title_font_size=18
time_font_size=18
tooltip_font_size=18
hover_effect=size,color
osc_color=#000000
window_title_color=#eff0f1
window_controls_color=#eff0f1
windowcontrols_close_hover=#c86454
windowcontrols_max_hover=#448aca
windowcontrols_min_hover=#448aca
title_color=#eff0f1
cache_info_color=#eff0f1
seekbarfg_color=#448aca
seekbarbg_color=#8d8f91
seekbar_cache_color=#538bbf
seek_handle_color=#448aca
volumebar_match_seek_color=no
time_color=#eff0f1
chapter_title_color=#eff0f1
side_buttons_color=#eff0f1
middle_buttons_color=#eff0f1
playpause_color=#eff0f1
held_element_color=#708da8
hover_effect_color=#488aca
thumbnail_box_color=#111111
thumbnail_box_outline=#404040
nibble_color=#708da8
nibble_current_color=#448aca
