#!/bin/sh


## start sxhkd
if [ $(ps -A -o cmd | grep -c '^sxhkd') -eq 0 ]
then
	sxhkd &
fi


## set wallpaper
hsetroot -cover $HOME/.config/wallpaper


## stop all statusbars
for pid in $(ps -A -o pid,cmd | awk '/[[:digit:]]+ perl .*statusbar.pl/ { print $1 }')
do
	kill -s KILL $pid
done


## (re)start unclutter
for pid in $(ps -A -o pid,cmd | awk '/[[:digit:]]+ unclutter/ { print $1 }')
do
	kill -s KILL $pid
done
unclutter --idle 5 --root &


## (re)start picom
for pid in $(ps -A -o pid,cmd | awk '/[[:digit:]]+ picom/ { print $1 }')
do
	kill -s KILL $pid
done
picom --daemon


## stop all subscriptions
for pid in $(ps -A -o pid,cmd | awk '/[[:digit:]]+ bspc subscribe/ { print $1 }')
do
	kill -s KILL $pid
done



#  Config
###########

bspc config normal_border_color '#002b36'
bspc config active_border_color '#268bd2'
bspc config focused_border_color '#2aa198'
bspc config presel_feedback_color '#2aa198'

bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

#bspc config directional_focus_tightness low
#bspc config removal_adjustment

bspc config presel_feedback true
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config single_monocle false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 focus
bspc config pointer_action3 resize_side
bspc config click_to_focus any
bspc config swallow_first_click false
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false

bspc config ignore_ewmh_focus false
bspc config	ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts false

bspc config center_pseudo_tiled true
bspc config honor_size_hints false
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors true

bspc config window_gap 8
bspc config border_width 2
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0


#  Rules
##########

bspc rule -a "Zathura" state=tiled


#  Workspaces
###############

## setup workspaces
case "$(uname -n)" in
	*-vbox )
		bspc monitor Virtual1 -d home1 media1 dev1 term1 other1
		$HOME/.config/statusbar/statusbar.pl Virtual1 &
		if [ $(xrandr | grep -c "Virtual2 connected") -eq 1 ]
		then
			bspc monitor Virtual2 -d home2 media2 dev2 term2 other2
			$HOME/.config/statusbar/statusbar.pl Virtual2 &
		fi
		;;
	* )
		# find first active monitor, use as fallback
		_monitor=$(xrandr --listactivemonitors | awk '/^[[:space:]]* 0:/ { print $(NF) }')
		bspc monitor "$_monitor" -d home1 media1 dev1 term1 other1
		$HOME/.config/statusbar/statusbar.pl "$_monitor" &
		;;
esac
: $(sleep 1 ; xdo lower -N dzen) &

## update statusbars on workspace switching
: $(sleep 1 ; bspc subscribe desktop | while read -r event
	do
		for _pid in $(ps -A -o pid,cmd | awk '/[[:digit:]] perl .*statusbar.pl/ { print $1 }')
		do
			kill -s HUP $_pid
		done
	done) &


